server:
  port: 5000

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  jackson:
    serialization:
      write-dates-as-timestamps: false



captcha:
  ttl: 180

redis:
  host: localhost
  port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

